### ISSUE TITLE
Missing call to drawMinimapImage() in "afterDrawing" function

### ISSUE THREAD

**Issue by wasimanitoba** [savkelita/vis-network-minimap#2]
In the callback function assigned to the _afterDrawing_ event listener, the minimap does not update the map view because it seems to be missing a call to drawMinimapImage() after the calling  drawRadar() in the final _else_ clause.

## Resolution:
After line #383 in [minimap.js](https://github.com/savkelita/vis-network-minimap/blob/master/js/minimap.js), add the following:
drawMinimapImage()

**Comment by savkelita** [comment]
Thank you @weswpg for suggestion.

The main idea is to capture whole VisNetwork inside minimap container and to put radar to follow your current position. This functionality is inspired by d3: https://codepen.io/refs/pen/QRYBzO

**Comment by AustinCasteel** [comment]
I don't know if I should start a new issue or reopen this one, but it does pertain to the initial issue.

For a static network map, the minimap works perfectly fine. However, if you have a dynamic network map it does not because the minimap image is not updated after the initial draw so any changes to the network are not shown in the minimap.

I have messed around with it for some time and for the life of me I can not get it to work correctly, probably due to something so simple, I am overlooking it. If I were to add `drawMinimapImage()` into the "afterDrawing" listener it does solve the issue of updating the image with any given change, however the minimap image "zooms in" when you zoom into the network and pans around as you do so thus breaking and defeating the purpose of the minimap.

Is there a way to have an always up-to-date minimap image with network changes while remaining static in scale & movement as the user moves around? Any thoughts or suggestions would be greatly appreciated.

**Comment by savkelita** [comment]
Hi @AustinCasteel,

I haven't used this library in a long time and I will have to remind myself how it works. I took a quick look at the [API Doc](https://visjs.github.io/vis-network/docs/network/#Events) and there is 'stabilization' function which fires when network has stabilised. Maybe that can be used to generate new minimap image and redraw the map. Definitely this is a feature and functionality that I plan to implement in a future. If you have any idea make a PR and I'll take a look.

**Comment by AustinCasteel** [comment]
Just talking through it roughly would be to use the `stabilization` listener, which at the moment of stabilization would take the coordinates and scale of the users viewing the network map, fit the network, render a new minimap image, and then put the user back to where they were in the network. This is very rough and I assume would introduce stutter due to how long it would take to run through the process compared to what's perceivable to users.

**Comment by savkelita** [comment]
@AustinCasteel I completely agree with you. Hm, maybe we need two maps, one to capture whole canvas and original one where the user interacts with. Capture is just for real picture of minimap and from the new state from the original one. Need to try it and maybe we gonna have performance issues on large maps. What do you think?

**Comment by AustinCasteel** [comment]
Due to how my map interactively draws and they can get very big, having two of the same map trying to mimic the exact same thing will degrade performance especially since I also have a btn to draw the full map all at once instead of interactively. Also when I had a node and it is stabilizing, there is no guarantee that the node will land at the exact same spot in both maps. So I would like to avoid that if possible.

Here is what I have right now. It works pretty well except there is one issue. So it follows the same process I talked through above, and all works except the "radar" block is not correct. I tried adding `drawRadar()` at the end but it does not appear to be doing anything at all. The "radar" does not update when it takes the user back to where they were (`moveTo`) on the map so it throws off the scale and translation of it.

>Note: I have the delays because if I don't everything just runs basically at once and does not work.

```js
var originalView, originalScale;

network.on('stabilized', () => {
    originalScale = network.getScale();
    originalView = network.getViewPosition();
    console.log("before fit:", originalView, originalScale);

    setTimeout(function () {
        network.fit();
        console.log("after fit:", network.getViewPosition(), network.getScale());
        setTimeout(function () {
            const minimapImage = document.getElementById('minimapImage');
            minimapImage.removeAttribute('src');
            drawMinimapImage();
            console.log("after image:", network.getViewPosition(), network.getScale());
            setTimeout(function () {
                network.moveTo({ position: originalView, scale: originalScale });
                console.log("after return:", network.getViewPosition(), network.getScale());
                setTimeout(function () {
                    drawRadar();
                    console.log("after radar");
                }, 100);
            }, 100);
        }, 100);
    }, 100);
})
```
